[config]

[templates.waybar]
input_path = '~/.config/matugen/templates/colors-waybar.css'
output_path = '~/.cache/matugen/colors-waybar.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wofi]
input_path = '~/.config/matugen/templates/colors-wofi.css'
output_path = '~/.cache/matugen/colors-wofi.css'

[templates.foot]
input_path = '~/.config/matugen/templates/foot-colors.ini'
output_path = '~/.cache/matugen/foot-colors.ini'

[templates.sway]
input_path = '~/.config/matugen/templates/colors-sway'
output_path = '~/.cache/matugen/colors-sway'
post_hook = 'swaymsg reload'

[templates.swaylock]
input_path = '~/.config/matugen/templates/swaylock'
output_path = '~/.cache/matugen/swaylock'
