# vim plugins
[".vim/pack/plugins/start/vim-sensible"]
    type = "git-repo"
    url = "https://github.com/tpope/vim-sensible.git"
    refreshPeriod = "720h"  # 30 days

[".vim/pack/plugins/start/vim-surround"]
    type = "git-repo"
    url = "https://github.com/tpope/vim-surround.git"
    refreshPeriod = "720h"

[".vim/pack/plugins/start/vim-commentary"]
    type = "git-repo"
    url = "https://github.com/tpope/vim-commentary.git"
    refreshPeriod = "720h"

[".vim/pack/plugins/start/vim-repeat"]
    type = "git-repo"
    url = "https://github.com/tpope/vim-repeat.git"
    refreshPeriod = "720h"

[".vim/pack/plugins/start/vim-fugitive"]
    type = "git-repo"
    url = "https://github.com/tpope/vim-fugitive.git"
    refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-gitgutter"]
    type = "git-repo"
    url = "https://github.com/airblade/vim-gitgutter.git"
    refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-mundo"]
    type = "git-repo"
    url = "https://github.com/simnalamburt/vim-mundo.git"
    refreshPeriod = "720h"

[".vim/pack/plugins/start/fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"

[".vim/pack/plugins/start/fzf.vim"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.vim.git"
    refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-polyglot"]
    type = "git-repo"
    url = "https://github.com/sheerun/vim-polyglot.git"
    refreshPeriod = "720h"
