##
# starship.toml config
##

# Get editor completions based on the config schema - if the lsp supports it
"$schema" = 'https://starship.rs/config-schema.json'

# key format for the line
format = """$cmd_duration\
$jobs\
$memory_usage\
$python\
[\\[](outline)\
$username\
[@](outline)\
$hostname\
[:](outline)\
$directory\
$git_branch\
$git_status\
$git_state\
[\\]](outline)\
$character"""

# don't add a blank link to the prompt
add_newline = false
# continuation just like bash
continuation_prompt = ">  "

# Use the Material You color palette
palette = 'matugen'

##
# Core prompt display - things you have to look at all the time
##
[username]
format = "[$user]($style)"
show_always = true
style_user = 'primary'

[hostname]
format = "[$hostname]($style)"
ssh_only = false
style = 'primary'

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncate_to_repo = true
#truncation_symbol = ".../"
style = 'primary'

[character]
success_symbol = "[\\$](outline)"
error_symbol = "[\\$](bold error)"

##
# Context-sensitive stuff - stuff that only pops up when you need it
##
[python]
format = """[\\[](outline)\
[(${version})(|$virtualenv)]($style)\
[\\]](outline)"""
version_format = "$major.$minor"

[jobs]
format = """[\\[](outline)\
[$symbol$number]($style)\
[\\]](outline)"""
symbol = ""
style = 'primary'

[cmd_duration]
disabled = true
format = """[\\[](outline)\
[$duration]($style)\
[\\]](outline)"""
style = 'error'
min_time = 30_000 # show anything longer than 30s
#show_notifications = true 
#min_time_to_notify = 60_000 # gui notification for anything longer than 60s

[git_branch]
format = """ [\\(](outline)\
[$symbol$branch(:$remote_branch)]($style)\
"""
symbol = ''
style = 'secondary'

[git_status]
format = """([\\[$all_status$ahead_behind\\]]($style))\
[\\)](outline)"""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[memory_usage]
format = """[$symbol${ram_pct}]($style)"""
symbol = ''
style = 'bold error'
disabled = false
threshold = 80

##
# Color palette
##
[palettes.matugen]
primary = '{{colors.primary.dark.hex}}'
secondary = '{{colors.secondary.dark.hex}}'
tertiary = '{{colors.tertiary.dark.hex}}'
error = '{{colors.error.dark.hex}}'
surface = '{{colors.surface.dark.hex}}'
on_surface = '{{colors.on_surface.dark.hex}}'
surface_variant = '{{colors.surface_variant.dark.hex}}'
on_surface_variant = '{{colors.on_surface_variant.dark.hex}}'
outline = '{{colors.outline.dark.hex}}'
