##
# starship.toml config
##

# Get editor completions based on the config schema - if the lsp supports it
"$schema" = 'https://starship.rs/config-schema.json'

# key format for the line
format = """$cmd_duration\
$jobs\
$memory_usage\
$python\
[\\[](outline)\
$username\
[@](outline)\
$hostname\
[:](outline)\
$directory\
$git_branch\
$git_status\
$git_state\
[\\]](outline)\
$character"""

# don't add a blank link to the prompt
add_newline = false
# continuation just like bash
continuation_prompt = ">  "

# Use the Material You color palette
palette = 'matugen'

##
# Core prompt display - things you have to look at all the time
##
[username]
format = "[$user]($style)"
show_always = true
style_user = 'primary'

[hostname]
format = "[$hostname]($style)"
ssh_only = false
style = 'primary'

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncate_to_repo = true
#truncation_symbol = ".../"
style = 'primary'
read_only = " 󰌾"
read_only_style = "error"

[character]
success_symbol = "[\\$](outline)"
error_symbol = "[\\$](bold error)"

##
# Context-sensitive stuff - stuff that only pops up when you need it
##
[python]
format = """[\\[](outline)\
[(${version})(|$virtualenv)]($style)\
[\\]](outline)"""
version_format = "$major.$minor"
style = "secondary"

[jobs]
format = """[\\[](outline)\
[$symbol$number]($style)\
[\\]](outline)"""
symbol = ""
style = 'primary'

[cmd_duration]
disabled = true
format = """[\\[](outline)\
[$duration]($style)\
[\\]](outline)"""
style = 'error'
min_time = 30_000 # show anything longer than 30s
#show_notifications = true 
#min_time_to_notify = 60_000 # gui notification for anything longer than 60s

[git_branch]
format = """ [\\(](outline)\
[$symbol$branch(:$remote_branch)]($style)\
"""
symbol = ''
style = 'secondary'

[git_status]
format = """([\\[$all_status$ahead_behind\\]]($style))\
[\\)](outline)"""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[memory_usage]
format = """[$symbol${ram_pct}]($style)"""
symbol = ''
style = 'bold error'
disabled = false
threshold = 80

##
# Color palette
##
[palettes.matugen]
# Primary colors
primary = '#aad290'
on_primary = '#183807'
primary_container = '#2e4f1c'
on_primary_container = '#c5efaa'
inverse_primary = '#456731'

# Secondary colors
secondary = '#bdcbaf'
on_secondary = '#283420'
secondary_container = '#3e4a35'
on_secondary_container = '#d9e7ca'

# Tertiary colors
tertiary = '#a0cfcf'
on_tertiary = '#003737'
tertiary_container = '#1e4e4e'
on_tertiary_container = '#bbebeb'

# Error colors
error = '#ffb4ab'
on_error = '#690005'
error_container = '#93000a'
on_error_container = '#ffdad6'

# Surface colors
surface = '#11140e'
on_surface = '#e1e4d9'
surface_variant = '#43483e'
on_surface_variant = '#c3c8bb'
surface_dim = '#11140e'
surface_bright = '#373a33'
surface_container = '#1d211a'
surface_container_high = '#282b24'
surface_container_highest = '#32362f'

# Inverse colors
inverse_surface = '#e1e4d9'
inverse_on_surface = '#2e312b'

# Outline colors
outline = '#8d9286'
outline_variant = '#43483e'

# Special colors
scrim = '#000000'
shadow = '#000000'
